
trigger:
- master
- develop
- release

jobs:
- job: 'Continuous_Integration'
  pool:
      #name: 'ARO_Agent'
      vmImage: ubuntu-latest
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'package -DskipTests'
      
  - task: CopyFiles@2
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/release', 'refs/heads/develop'))
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: |
        **
        !.git/**/*
        !**.md
        !**.gitignore
        !**.yml

  - task: ArchiveFiles@2
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/release', 'refs/heads/develop'))
    displayName: 'Compress: $(Build.ArtifactStagingDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/_ci-ms-rfc-sap.tar'
      tarCompression: none
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/release', 'refs/heads/develop'))
    displayName: 'Publish Artifact: artifacts'
    inputs:
      ArtifactName: artifacts
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/_ci-ms-rfc-sap.tar'
  
