sap:
  datasource:
    sysnr: ${SYSNR}
    host: ${HOST}
    client: ${CLIENT}
    user: ${USER}
    password: ${PASSWORD}
    lang: ${LANG}
server:
  port: ${PORT}
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: ${TIME_OUT}